import type {
  ServiceType,
  Vendor,
  Order,
  Address,
  Coupon,
  Review,
  DeliveryTask,
  Notification,
  AdminKpi,
} from "./types";

// ============================================================================
// LAUNDRY SERVICES CATALOG
// ============================================================================
export const SERVICES: ServiceType[] = [
  {
    key: "wash_fold",
    name: "Wash & Fold",
    description: "Daily wear washed with care, tumble-dried and neatly folded.",
    icon: "WashingMachine",
    pricingType: "per_kg",
    basePrice: 60,
    expressMultiplier: 1.5,
    gradient: "from-teal-400 to-cyan-500",
    category: "everyday",
  },
  {
    key: "wash_iron",
    name: "Wash & Iron",
    description: "Crisply pressed shirts and formals, ready to wear.",
    icon: "Shirt",
    pricingType: "per_piece",
    basePrice: 15,
    expressMultiplier: 1.5,
    gradient: "from-emerald-400 to-teal-500",
    category: "everyday",
  },
  {
    key: "dry_cleaning",
    name: "Dry Cleaning",
    description: "Solvent-based care for suits, sarees and delicate fabrics.",
    icon: "Sparkles",
    pricingType: "per_piece",
    basePrice: 120,
    expressMultiplier: 1.8,
    gradient: "from-violet-400 to-purple-500",
    category: "premium",
  },
  {
    key: "steam_ironing",
    name: "Steam Ironing",
    description: "Professional steam press for a flawless finish.",
    icon: "Wind",
    pricingType: "per_piece",
    basePrice: 18,
    expressMultiplier: 1.6,
    gradient: "from-sky-400 to-cyan-500",
    category: "everyday",
  },
  {
    key: "premium_care",
    name: "Premium Garment Care",
    description: "Bespoke treatment for designer and luxury garments.",
    icon: "Crown",
    pricingType: "per_piece",
    basePrice: 250,
    expressMultiplier: 2,
    gradient: "from-amber-400 to-orange-500",
    category: "premium",
  },
  {
    key: "delicate_care",
    name: "Delicate Fabric Care",
    description: "Hand-finished care for silks, lace and woolens.",
    icon: "Feather",
    pricingType: "per_piece",
    basePrice: 180,
    expressMultiplier: 1.8,
    gradient: "from-pink-400 to-rose-500",
    category: "premium",
  },
  {
    key: "shoe_cleaning",
    name: "Shoe Cleaning",
    description: "Sneakers, formals and heels — refreshed and deodorised.",
    icon: "Footprints",
    pricingType: "per_piece",
    basePrice: 149,
    expressMultiplier: 1.5,
    gradient: "from-slate-400 to-slate-600",
    category: "specialty",
  },
  {
    key: "blanket",
    name: "Blanket Cleaning",
    description: "Deep-clean bulky blankets, quilts and comforters.",
    icon: "BedDouble",
    pricingType: "per_piece",
    basePrice: 199,
    expressMultiplier: 1.4,
    gradient: "from-orange-400 to-red-500",
    category: "specialty",
  },
  {
    key: "curtain",
    name: "Curtain Cleaning",
    description: "On-site pickup and pressing for curtains and drapes.",
    icon: "Blinds",
    pricingType: "per_piece",
    basePrice: 220,
    expressMultiplier: 1.4,
    gradient: "from-lime-400 to-emerald-500",
    category: "specialty",
  },
  {
    key: "carpet",
    name: "Carpet Cleaning",
    description: "Hot-extraction cleaning for rugs and carpets.",
    icon: "Square",
    pricingType: "per_piece",
    basePrice: 499,
    expressMultiplier: 1.3,
    gradient: "from-rose-400 to-pink-500",
    category: "specialty",
  },
  {
    key: "bulk",
    name: "Bulk Laundry",
    description: "Volume pricing for hostels, PGs and offices.",
    icon: "Package",
    pricingType: "per_kg",
    basePrice: 45,
    expressMultiplier: 1.2,
    gradient: "from-cyan-400 to-blue-500",
    category: "bulk",
  },
];

// ============================================================================
// VENDORS
// ============================================================================
export const VENDORS: Vendor[] = [
  {
    id: "v1",
    name: "FreshFold Laundry Co.",
    rating: 4.8,
    reviewCount: 1247,
    distanceKm: 1.2,
    area: "Indiranagar",
    city: "Bengaluru",
    estimatedDeliveryHrs: 24,
    isOpen: true,
    tags: ["Eco-friendly", "Express available", "Premium"],
    servicesOffered: ["wash_fold", "wash_iron", "dry_cleaning", "steam_ironing", "premium_care"],
    priceLevel: 2,
    logoColor: "bg-primary-surface",
    logoInitials: "FF",
    capacityUsedPct: 62,
    repeatCustomerRate: 78,
    avgTurnaroundHrs: 22,
    monthlyRevenue: 428000,
    verified: true,
    kycStatus: "approved",
    joinedDate: "2023-03-14",
    totalOrders: 8421,
    responseTimeMins: 4,
  },
  {
    id: "v2",
    name: "Pristine Wash Hub",
    rating: 4.9,
    reviewCount: 892,
    distanceKm: 2.4,
    area: "Koramangala",
    city: "Bengaluru",
    estimatedDeliveryHrs: 20,
    isOpen: true,
    tags: ["Top rated", "24/7", "Designer care"],
    servicesOffered: ["wash_fold", "wash_iron", "dry_cleaning", "delicate_care", "premium_care"],
    priceLevel: 3,
    logoColor: "bg-primary-surface",
    logoInitials: "PW",
    capacityUsedPct: 78,
    repeatCustomerRate: 85,
    avgTurnaroundHrs: 19,
    monthlyRevenue: 612000,
    verified: true,
    kycStatus: "approved",
    joinedDate: "2022-11-02",
    totalOrders: 11240,
    responseTimeMins: 2,
  },
  {
    id: "v3",
    name: "QuickClean Express",
    rating: 4.5,
    reviewCount: 534,
    distanceKm: 0.8,
    area: "HSR Layout",
    city: "Bengaluru",
    estimatedDeliveryHrs: 12,
    isOpen: true,
    tags: ["Fastest", "Budget friendly", "Express"],
    servicesOffered: ["wash_fold", "wash_iron", "bulk"],
    priceLevel: 1,
    logoColor: "bg-primary-surface",
    logoInitials: "QC",
    capacityUsedPct: 45,
    repeatCustomerRate: 64,
    avgTurnaroundHrs: 11,
    monthlyRevenue: 198000,
    verified: true,
    kycStatus: "approved",
    joinedDate: "2024-01-20",
    totalOrders: 4218,
    responseTimeMins: 6,
  },
  {
    id: "v4",
    name: "Royal Garment Care",
    rating: 4.7,
    reviewCount: 678,
    distanceKm: 3.6,
    area: "Jayanagar",
    city: "Bengaluru",
    estimatedDeliveryHrs: 36,
    isOpen: true,
    tags: ["Luxury", "Wedding wear", "Saree specialist"],
    servicesOffered: ["dry_cleaning", "premium_care", "delicate_care", "steam_ironing"],
    priceLevel: 3,
    logoColor: "bg-primary-surface",
    logoInitials: "RG",
    capacityUsedPct: 71,
    repeatCustomerRate: 81,
    avgTurnaroundHrs: 32,
    monthlyRevenue: 524000,
    verified: true,
    kycStatus: "approved",
    joinedDate: "2022-07-08",
    totalOrders: 6192,
    responseTimeMins: 3,
  },
  {
    id: "v5",
    name: "Sparkle Laundry Studio",
    rating: 4.6,
    reviewCount: 412,
    distanceKm: 4.1,
    area: "BTM Layout",
    city: "Bengaluru",
    estimatedDeliveryHrs: 28,
    isOpen: false,
    tags: ["Specialty", "Curtain experts"],
    servicesOffered: ["wash_fold", "wash_iron", "curtain", "blanket", "carpet"],
    priceLevel: 2,
    logoColor: "bg-primary-surface",
    logoInitials: "SL",
    capacityUsedPct: 88,
    repeatCustomerRate: 73,
    avgTurnaroundHrs: 26,
    monthlyRevenue: 312000,
    verified: true,
    kycStatus: "approved",
    joinedDate: "2023-06-19",
    totalOrders: 3987,
    responseTimeMins: 5,
  },
  {
    id: "v6",
    name: "UrbanFresh Laundry",
    rating: 4.4,
    reviewCount: 287,
    distanceKm: 5.2,
    area: "Whitefield",
    city: "Bengaluru",
    estimatedDeliveryHrs: 30,
    isOpen: true,
    tags: ["Bulk orders", "PG friendly"],
    servicesOffered: ["wash_fold", "wash_iron", "shoe_cleaning", "bulk"],
    priceLevel: 1,
    logoColor: "bg-primary-surface",
    logoInitials: "UF",
    capacityUsedPct: 54,
    repeatCustomerRate: 68,
    avgTurnaroundHrs: 28,
    monthlyRevenue: 168000,
    verified: true,
    kycStatus: "pending",
    joinedDate: "2024-09-01",
    totalOrders: 2104,
    responseTimeMins: 9,
  },
];

// ============================================================================
// ORDER STAGE DEFINITIONS
// ============================================================================
export const ORDER_STAGE_FLOW: { stage: Order["status"]; label: string; icon: string }[] = [
  { stage: "placed", label: "Order Placed", icon: "ClipboardCheck" },
  { stage: "vendor_assigned", label: "Vendor Assigned", icon: "Store" },
  { stage: "vendor_accepted", label: "Vendor Accepted", icon: "BadgeCheck" },
  { stage: "pickup_scheduled", label: "Pickup Scheduled", icon: "CalendarClock" },
  { stage: "pickup_completed", label: "Pickup Completed", icon: "PackageCheck" },
  { stage: "laundry_received", label: "Laundry Received", icon: "Boxes" },
  { stage: "sorting", label: "Sorting", icon: "ListTree" },
  { stage: "tagging", label: "Tagging", icon: "Tag" },
  { stage: "washing", label: "Washing", icon: "WashingMachine" },
  { stage: "drying", label: "Drying", icon: "Wind" },
  { stage: "ironing", label: "Ironing", icon: "Shirt" },
  { stage: "dry_cleaning", label: "Dry Cleaning", icon: "Sparkles" },
  { stage: "quality_inspection", label: "Quality Inspection", icon: "SearchCheck" },
  { stage: "packing", label: "Packing", icon: "Package" },
  { stage: "ready_for_dispatch", label: "Ready for Dispatch", icon: "Truck" },
  { stage: "out_for_delivery", label: "Out for Delivery", icon: "Bike" },
  { stage: "delivered", label: "Delivered", icon: "Home" },
  { stage: "completed", label: "Completed", icon: "CircleCheck" },
];

function buildStages(currentIndex: number, baseDate: Date) {
  return ORDER_STAGE_FLOW.map((s, i) => {
    const ts = new Date(baseDate.getTime() + i * 90 * 60 * 1000);
    return {
      stage: s.stage,
      label: s.label,
      timestamp: i <= currentIndex ? ts.toISOString() : "",
      done: i <= currentIndex,
    };
  });
}

// ============================================================================
// ORDERS
// ============================================================================
export const ORDERS: Order[] = [
  {
    id: "o1",
    code: "LH-2847",
    customerId: "c1",
    customerName: "Aarav Mehta",
    customerAvatar: "AM",
    vendorId: "v1",
    vendorName: "FreshFold Laundry Co.",
    vendorLogoInitials: "FF",
    vendorLogoColor: "bg-primary-surface",
    deliveryExecutiveId: "d1",
    deliveryExecutiveName: "Rajesh Kumar",
    status: "washing",
    currentStageIndex: 8,
    stages: buildStages(8, new Date(Date.now() - 12 * 3600 * 1000)),
    items: [
      { serviceKey: "wash_fold", serviceName: "Wash & Fold", qty: 5, unit: "kg", unitPrice: 60, express: false },
      { serviceKey: "wash_iron", serviceName: "Wash & Iron", qty: 6, unit: "piece", unitPrice: 15, express: false },
    ],
    pickupAddress: "Flat 402, Skyline Residency, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-12",
    pickupSlot: "10:00 AM – 12:00 PM",
    deliveryDate: "2026-07-13",
    deliverySlot: "6:00 PM – 8:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
    amount: 390,
    taxes: 70.2,
    platformFee: 25,
    deliveryFee: 40,
    total: 525.2,
    paymentMethod: "UPI",
    paymentStatus: "paid",
    express: false,
    notes: "Please use mild detergent for baby clothes.",
    garmentCount: 11,
    weightKg: 5,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    aiPrediction: { confidence: 0.94, estimatedCompletionHrs: 14, delayRisk: "low" },
  },
  {
    id: "o2",
    code: "LH-2848",
    customerId: "c1",
    customerName: "Aarav Mehta",
    customerAvatar: "AM",
    vendorId: "v2",
    vendorName: "Pristine Wash Hub",
    vendorLogoInitials: "PW",
    vendorLogoColor: "bg-primary-surface",
    status: "out_for_delivery",
    currentStageIndex: 15,
    stages: buildStages(15, new Date(Date.now() - 30 * 3600 * 1000)),
    items: [
      { serviceKey: "dry_cleaning", serviceName: "Dry Cleaning", qty: 3, unit: "piece", unitPrice: 120, express: true },
      { serviceKey: "premium_care", serviceName: "Premium Garment Care", qty: 1, unit: "piece", unitPrice: 250, express: true },
    ],
    pickupAddress: "Flat 402, Skyline Residency, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-11",
    pickupSlot: "4:00 PM – 6:00 PM",
    deliveryDate: "2026-07-12",
    deliverySlot: "12:00 PM – 2:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 1 * 3600 * 1000).toISOString(),
    amount: 851,
    taxes: 153.2,
    platformFee: 25,
    deliveryFee: 40,
    total: 1069.2,
    paymentMethod: "Credit Card",
    paymentStatus: "paid",
    express: true,
    notes: "Wedding sherwani — handle with extra care.",
    garmentCount: 4,
    createdAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    aiPrediction: { confidence: 0.97, estimatedCompletionHrs: 1, delayRisk: "low" },
  },
  {
    id: "o3",
    code: "LH-2849",
    customerId: "c1",
    customerName: "Aarav Mehta",
    customerAvatar: "AM",
    vendorId: "v3",
    vendorName: "QuickClean Express",
    vendorLogoInitials: "QC",
    vendorLogoColor: "bg-primary-surface",
    status: "placed",
    currentStageIndex: 0,
    stages: buildStages(0, new Date()),
    items: [
      { serviceKey: "wash_iron", serviceName: "Wash & Iron", qty: 10, unit: "piece", unitPrice: 15, express: false },
    ],
    pickupAddress: "Flat 402, Skyline Residency, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-12",
    pickupSlot: "2:00 PM – 4:00 PM",
    deliveryDate: "2026-07-13",
    deliverySlot: "10:00 AM – 12:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 22 * 3600 * 1000).toISOString(),
    amount: 150,
    taxes: 27,
    platformFee: 15,
    deliveryFee: 30,
    total: 222,
    paymentMethod: "Wallet",
    paymentStatus: "pending",
    express: false,
    garmentCount: 10,
    createdAt: new Date().toISOString(),
    aiPrediction: { confidence: 0.91, estimatedCompletionHrs: 22, delayRisk: "medium", delayReason: "High vendor capacity utilisation" },
  },
  {
    id: "o4",
    code: "LH-2821",
    customerId: "c1",
    customerName: "Aarav Mehta",
    customerAvatar: "AM",
    vendorId: "v1",
    vendorName: "FreshFold Laundry Co.",
    vendorLogoInitials: "FF",
    vendorLogoColor: "bg-primary-surface",
    status: "completed",
    currentStageIndex: 17,
    stages: buildStages(17, new Date(Date.now() - 96 * 3600 * 1000)),
    items: [
      { serviceKey: "wash_fold", serviceName: "Wash & Fold", qty: 7, unit: "kg", unitPrice: 60, express: false },
      { serviceKey: "blanket", serviceName: "Blanket Cleaning", qty: 1, unit: "piece", unitPrice: 199, express: false },
    ],
    pickupAddress: "Flat 402, Skyline Residency, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-07",
    pickupSlot: "10:00 AM – 12:00 PM",
    deliveryDate: "2026-07-09",
    deliverySlot: "6:00 PM – 8:00 PM",
    estimatedDeliveryAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    amount: 619,
    taxes: 111.4,
    platformFee: 25,
    deliveryFee: 40,
    total: 795.4,
    paymentMethod: "UPI",
    paymentStatus: "paid",
    express: false,
    garmentCount: 8,
    weightKg: 7,
    createdAt: new Date(Date.now() - 96 * 3600 * 1000).toISOString(),
    aiPrediction: { confidence: 0.96, estimatedCompletionHrs: 0, delayRisk: "low" },
  },
  {
    id: "o5",
    code: "LH-2810",
    customerId: "c1",
    customerName: "Aarav Mehta",
    customerAvatar: "AM",
    vendorId: "v4",
    vendorName: "Royal Garment Care",
    vendorLogoInitials: "RG",
    vendorLogoColor: "bg-primary-surface",
    status: "completed",
    currentStageIndex: 17,
    stages: buildStages(17, new Date(Date.now() - 168 * 3600 * 1000)),
    items: [
      { serviceKey: "dry_cleaning", serviceName: "Dry Cleaning", qty: 5, unit: "piece", unitPrice: 120, express: false },
      { serviceKey: "delicate_care", serviceName: "Delicate Fabric Care", qty: 2, unit: "piece", unitPrice: 180, express: false },
    ],
    pickupAddress: "Flat 402, Skyline Residency, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-03",
    pickupSlot: "4:00 PM – 6:00 PM",
    deliveryDate: "2026-07-05",
    deliverySlot: "12:00 PM – 2:00 PM",
    estimatedDeliveryAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    amount: 960,
    taxes: 172.8,
    platformFee: 25,
    deliveryFee: 40,
    total: 1197.8,
    paymentMethod: "Credit Card",
    paymentStatus: "paid",
    express: false,
    garmentCount: 7,
    createdAt: new Date(Date.now() - 168 * 3600 * 1000).toISOString(),
    aiPrediction: { confidence: 0.93, estimatedCompletionHrs: 0, delayRisk: "low" },
  },
];

// Vendor-side orders (additional ones for vendor view)
export const VENDOR_ORDERS: Order[] = [
  {
    id: "vo1",
    code: "LH-2850",
    customerId: "c2",
    customerName: "Priya Sharma",
    customerAvatar: "PS",
    vendorId: "v1",
    vendorName: "FreshFold Laundry Co.",
    vendorLogoInitials: "FF",
    vendorLogoColor: "bg-primary-surface",
    status: "ironing",
    currentStageIndex: 10,
    stages: buildStages(10, new Date(Date.now() - 8 * 3600 * 1000)),
    items: [
      { serviceKey: "wash_iron", serviceName: "Wash & Iron", qty: 12, unit: "piece", unitPrice: 15, express: false },
    ],
    pickupAddress: "12, 100ft Road, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-12",
    pickupSlot: "8:00 AM – 10:00 AM",
    deliveryDate: "2026-07-13",
    deliverySlot: "6:00 PM – 8:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
    amount: 180,
    taxes: 32.4,
    platformFee: 20,
    deliveryFee: 35,
    total: 267.4,
    paymentMethod: "UPI",
    paymentStatus: "paid",
    express: false,
    garmentCount: 12,
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    aiPrediction: { confidence: 0.92, estimatedCompletionHrs: 10, delayRisk: "low" },
  },
  {
    id: "vo2",
    code: "LH-2851",
    customerId: "c3",
    customerName: "Rohan Gupta",
    customerAvatar: "RG",
    vendorId: "v1",
    vendorName: "FreshFold Laundry Co.",
    vendorLogoInitials: "FF",
    vendorLogoColor: "bg-primary-surface",
    status: "pickup_scheduled",
    currentStageIndex: 3,
    stages: buildStages(3, new Date(Date.now() - 2 * 3600 * 1000)),
    items: [
      { serviceKey: "wash_fold", serviceName: "Wash & Fold", qty: 4, unit: "kg", unitPrice: 60, express: true },
    ],
    pickupAddress: "560, 6th Main, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-12",
    pickupSlot: "12:00 PM – 2:00 PM",
    deliveryDate: "2026-07-12",
    deliverySlot: "8:00 PM – 10:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    amount: 360,
    taxes: 64.8,
    platformFee: 25,
    deliveryFee: 40,
    total: 489.8,
    paymentMethod: "Wallet",
    paymentStatus: "paid",
    express: true,
    garmentCount: 4,
    weightKg: 4,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    aiPrediction: { confidence: 0.95, estimatedCompletionHrs: 8, delayRisk: "low" },
  },
  {
    id: "vo3",
    code: "LH-2852",
    customerId: "c4",
    customerName: "Sneha Reddy",
    customerAvatar: "SR",
    vendorId: "v1",
    vendorName: "FreshFold Laundry Co.",
    vendorLogoInitials: "FF",
    vendorLogoColor: "bg-primary-surface",
    status: "vendor_accepted",
    currentStageIndex: 2,
    stages: buildStages(2, new Date(Date.now() - 1 * 3600 * 1000)),
    items: [
      { serviceKey: "dry_cleaning", serviceName: "Dry Cleaning", qty: 4, unit: "piece", unitPrice: 120, express: false },
    ],
    pickupAddress: "Apartment 7B, HAL 2nd Stage",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-12",
    pickupSlot: "4:00 PM – 6:00 PM",
    deliveryDate: "2026-07-14",
    deliverySlot: "12:00 PM – 2:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 40 * 3600 * 1000).toISOString(),
    amount: 480,
    taxes: 86.4,
    platformFee: 25,
    deliveryFee: 40,
    total: 631.4,
    paymentMethod: "Credit Card",
    paymentStatus: "pending",
    express: false,
    garmentCount: 4,
    createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    aiPrediction: { confidence: 0.89, estimatedCompletionHrs: 40, delayRisk: "medium", delayReason: "Dry cleaning queue full" },
  },
  {
    id: "vo4",
    code: "LH-2853",
    customerId: "c5",
    customerName: "Karthik R",
    customerAvatar: "KR",
    vendorId: "v1",
    vendorName: "FreshFold Laundry Co.",
    vendorLogoInitials: "FF",
    vendorLogoColor: "bg-primary-surface",
    status: "placed",
    currentStageIndex: 0,
    stages: buildStages(0, new Date()),
    items: [
      { serviceKey: "wash_fold", serviceName: "Wash & Fold", qty: 3, unit: "kg", unitPrice: 60, express: false },
    ],
    pickupAddress: "44, 6th Cross, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-13",
    pickupSlot: "10:00 AM – 12:00 PM",
    deliveryDate: "2026-07-14",
    deliverySlot: "6:00 PM – 8:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 28 * 3600 * 1000).toISOString(),
    amount: 180,
    taxes: 32.4,
    platformFee: 20,
    deliveryFee: 35,
    total: 267.4,
    paymentMethod: "UPI",
    paymentStatus: "paid",
    express: false,
    garmentCount: 3,
    weightKg: 3,
    createdAt: new Date().toISOString(),
    aiPrediction: { confidence: 0.93, estimatedCompletionHrs: 28, delayRisk: "low" },
  },
  {
    id: "vo5",
    code: "LH-2854",
    customerId: "c6",
    customerName: "Ananya Rao",
    customerAvatar: "AR",
    vendorId: "v1",
    vendorName: "FreshFold Laundry Co.",
    vendorLogoInitials: "FF",
    vendorLogoColor: "bg-primary-surface",
    status: "vendor_assigned",
    currentStageIndex: 1,
    stages: buildStages(1, new Date(Date.now() - 15 * 60 * 1000)),
    items: [
      { serviceKey: "dry_cleaning", serviceName: "Dry Cleaning", qty: 2, unit: "piece", unitPrice: 120, express: false },
      { serviceKey: "steam_ironing", serviceName: "Steam Ironing", qty: 5, unit: "piece", unitPrice: 18, express: false },
    ],
    pickupAddress: "210, HAL 2nd Stage, Indiranagar",
    pickupArea: "Indiranagar",
    pickupDate: "2026-07-13",
    pickupSlot: "4:00 PM – 6:00 PM",
    deliveryDate: "2026-07-15",
    deliverySlot: "12:00 PM – 2:00 PM",
    estimatedDeliveryAt: new Date(Date.now() + 44 * 3600 * 1000).toISOString(),
    amount: 330,
    taxes: 59.4,
    platformFee: 25,
    deliveryFee: 40,
    total: 454.4,
    paymentMethod: "Credit Card",
    paymentStatus: "paid",
    express: false,
    garmentCount: 7,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    aiPrediction: { confidence: 0.91, estimatedCompletionHrs: 44, delayRisk: "low" },
  },
];

// ============================================================================
// ADDRESSES
// ============================================================================
export const ADDRESSES: Address[] = [
  {
    id: "a1",
    label: "Home",
    line: "Flat 402, Skyline Residency, 100ft Road",
    area: "Indiranagar",
    city: "Bengaluru",
    pincode: "560038",
    isDefault: true,
    lat: 12.9719,
    lng: 77.6412,
  },
  {
    id: "a2",
    label: "Work",
    line: "Tower B, Prestige Tech Park, Marathahalli",
    area: "Kadubeesanahalli",
    city: "Bengaluru",
    pincode: "560103",
    isDefault: false,
    lat: 12.9352,
    lng: 77.6866,
  },
  {
    id: "a3",
    label: "Mom's Place",
    line: "24, 7th Cross, Jayanagar 4th Block",
    area: "Jayanagar",
    city: "Bengaluru",
    pincode: "560011",
    isDefault: false,
    lat: 12.9279,
    lng: 77.5835,
  },
];

// ============================================================================
// COUPONS
// ============================================================================
export const COUPONS: Coupon[] = [
  {
    code: "FRESH50",
    description: "50% off on your first order",
    discountPct: 50,
    maxDiscount: 150,
    minOrder: 200,
    expiresAt: "2026-07-31",
    type: "percentage",
  },
  {
    code: "WEEKEND25",
    description: "Weekend special — 25% off",
    discountPct: 25,
    maxDiscount: 100,
    minOrder: 300,
    expiresAt: "2026-07-14",
    type: "percentage",
  },
  {
    code: "FLAT75",
    description: "Flat ₹75 off on orders above ₹500",
    discountPct: 0,
    maxDiscount: 75,
    minOrder: 500,
    expiresAt: "2026-07-20",
    type: "flat",
  },
  {
    code: "EXPRESS10",
    description: "10% off on express orders",
    discountPct: 10,
    maxDiscount: 60,
    minOrder: 250,
    expiresAt: "2026-08-15",
    type: "percentage",
  },
];

// ============================================================================
// REVIEWS
// ============================================================================
export const REVIEWS: Review[] = [
  {
    id: "r1",
    orderId: "LH-2821",
    customerName: "Aarav Mehta",
    customerAvatar: "AM",
    vendorName: "FreshFold Laundry Co.",
    date: "2026-07-09",
    overall: 5,
    vendor: 5,
    pickup: 4,
    laundry: 5,
    delivery: 5,
    comment: "Stain on my white shirt was completely gone! Pickup was 10 mins early, delivery was perfectly folded. Will use again.",
    helpful: 14,
    vendorReply: "Thank you Aarav! We treat every garment like our own. See you next time 🙂",
  },
  {
    id: "r2",
    orderId: "LH-2810",
    customerName: "Aarav Mehta",
    customerAvatar: "AM",
    vendorName: "Royal Garment Care",
    date: "2026-07-05",
    overall: 5,
    vendor: 5,
    pickup: 5,
    laundry: 5,
    delivery: 4,
    comment: "My silk saree came back looking brand new. The dry-cleaning finish is unmatched. Worth every rupee.",
    helpful: 22,
    vendorReply: "Sarees are our speciality! Glad you loved the finish.",
  },
  {
    id: "r3",
    orderId: "LH-2799",
    customerName: "Priya Sharma",
    customerAvatar: "PS",
    vendorName: "FreshFold Laundry Co.",
    date: "2026-07-08",
    overall: 4,
    vendor: 4,
    pickup: 5,
    laundry: 4,
    delivery: 4,
    comment: "Great service overall, but delivery was slightly delayed. Laundry quality is excellent though.",
    helpful: 7,
  },
];

// ============================================================================
// DELIVERY EXECUTIVE TASKS
// ============================================================================
export const DELIVERY_TASKS: DeliveryTask[] = [
  {
    id: "dt1",
    type: "pickup",
    orderId: "o3",
    orderCode: "LH-2849",
    customerName: "Aarav Mehta",
    customerPhone: "+91 98765 43210",
    vendorName: "QuickClean Express",
    vendorPhone: "+91 91234 56780",
    address: "Flat 402, Skyline Residency, 100ft Road, Indiranagar",
    area: "Indiranagar",
    distanceKm: 1.4,
    slot: "2:00 PM – 4:00 PM",
    status: "pending",
    estimatedMins: 12,
    paymentMode: "Wallet",
    amount: 222,
    items: "10 shirts (Wash & Iron)",
  },
  {
    id: "dt2",
    type: "delivery",
    orderId: "o2",
    orderCode: "LH-2848",
    customerName: "Aarav Mehta",
    customerPhone: "+91 98765 43210",
    vendorName: "Pristine Wash Hub",
    vendorPhone: "+91 99887 76655",
    address: "Flat 402, Skyline Residency, 100ft Road, Indiranagar",
    area: "Indiranagar",
    distanceKm: 2.1,
    slot: "12:00 PM – 2:00 PM",
    status: "out_for_delivery",
    estimatedMins: 18,
    paymentMode: "Prepaid",
    amount: 0,
    items: "3 dry-clean items + 1 premium care (Express)",
  },
  {
    id: "dt3",
    type: "pickup",
    orderId: "vo3",
    orderCode: "LH-2852",
    customerName: "Sneha Reddy",
    customerPhone: "+91 90123 45678",
    vendorName: "FreshFold Laundry Co.",
    vendorPhone: "+91 91234 56780",
    address: "Apartment 7B, HAL 2nd Stage, Indiranagar",
    area: "Indiranagar",
    distanceKm: 0.9,
    slot: "4:00 PM – 6:00 PM",
    status: "pending",
    estimatedMins: 8,
    paymentMode: "Cash on Delivery",
    amount: 631.4,
    items: "4 dry-clean items",
  },
  {
    id: "dt4",
    type: "delivery",
    orderId: "vo1",
    orderCode: "LH-2850",
    customerName: "Priya Sharma",
    customerPhone: "+91 99887 76655",
    vendorName: "FreshFold Laundry Co.",
    vendorPhone: "+91 91234 56780",
    address: "12, 100ft Road, Indiranagar",
    area: "Indiranagar",
    distanceKm: 1.1,
    slot: "6:00 PM – 8:00 PM",
    status: "ready_for_delivery",
    estimatedMins: 15,
    paymentMode: "Prepaid",
    amount: 0,
    items: "12 shirts (Wash & Iron)",
  },
];

// ============================================================================
// NOTIFICATIONS
// ============================================================================
export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "ai",
    title: "AI Prediction",
    body: "Order LH-2849 has a medium delay risk. Vendor capacity at 78%.",
    time: "5 min ago",
    read: false,
    channel: "push",
  },
  {
    id: "n2",
    type: "vendor",
    title: "Vendor Accepted",
    body: "FreshFold Laundry Co. accepted your order LH-2847.",
    time: "32 min ago",
    read: false,
    channel: "push",
  },
  {
    id: "n3",
    type: "pickup",
    title: "Pickup Reminder",
    body: "Rajesh will arrive in 15 mins for order LH-2849 pickup.",
    time: "1 hour ago",
    read: false,
    channel: "sms",
  },
  {
    id: "n4",
    type: "delivery",
    title: "Out for Delivery",
    body: "Order LH-2848 is out for delivery. Arrives in ~1 hour.",
    time: "2 hours ago",
    read: true,
    channel: "push",
  },
  {
    id: "n5",
    type: "payment",
    title: "Payment Success",
    body: "₹525.20 paid via UPI for order LH-2847.",
    time: "12 hours ago",
    read: true,
    channel: "email",
  },
  {
    id: "n6",
    type: "promo",
    title: "Weekend Special",
    body: "Use code WEEKEND25 for 25% off this weekend!",
    time: "1 day ago",
    read: true,
    channel: "whatsapp",
  },
  {
    id: "n7",
    type: "booking",
    title: "Booking Confirmed",
    body: "Your order LH-2849 has been placed successfully.",
    time: "1 day ago",
    read: true,
    channel: "push",
  },
];

// ============================================================================
// ADMIN KPIs
// ============================================================================
export const ADMIN_KPIS: AdminKpi[] = [
  {
    label: "Total Customers",
    value: "48,210",
    change: 12.4,
    trend: "up",
    spark: [38, 40, 41, 43, 45, 46, 48],
    icon: "Users",
    accent: "bg-primary-surface",
  },
  {
    label: "Active Vendors",
    value: "1,284",
    change: 8.1,
    trend: "up",
    spark: [1100, 1150, 1180, 1210, 1240, 1260, 1284],
    icon: "Store",
    accent: "bg-primary-surface",
  },
  {
    label: "Live Orders",
    value: "642",
    change: 5.7,
    trend: "up",
    spark: [580, 600, 590, 610, 630, 620, 642],
    icon: "Activity",
    accent: "bg-primary-surface",
  },
  {
    label: "Monthly Revenue",
    value: "₹62.4L",
    change: 18.9,
    trend: "up",
    spark: [42, 48, 52, 55, 58, 60, 62.4],
    icon: "IndianRupee",
    accent: "bg-primary-surface",
  },
  {
    label: "Commission Earned",
    value: "₹6.24L",
    change: 18.9,
    trend: "up",
    spark: [4.2, 4.8, 5.2, 5.5, 5.8, 6.0, 6.24],
    icon: "Percent",
    accent: "bg-primary-surface",
  },
  {
    label: "Customer Satisfaction",
    value: "4.78 / 5",
    change: 2.3,
    trend: "up",
    spark: [4.6, 4.65, 4.7, 4.72, 4.75, 4.76, 4.78],
    icon: "Smile",
    accent: "from-sky-500 to-cyan-600",
  },
  {
    label: "Avg Turnaround",
    value: "21.4 hrs",
    change: -6.2,
    trend: "down",
    spark: [26, 25, 24, 23, 22.5, 22, 21.4],
    icon: "Clock",
    accent: "from-lime-500 to-emerald-600",
  },
  {
    label: "Cancellation Rate",
    value: "2.1%",
    change: -0.4,
    trend: "down",
    spark: [3.2, 3.0, 2.8, 2.6, 2.4, 2.2, 2.1],
    icon: "XCircle",
    accent: "from-red-500 to-rose-600",
  },
];

// ============================================================================
// REVENUE CHART DATA (last 7 months)
// ============================================================================
export const REVENUE_CHART = [
  { month: "Jan", revenue: 38.2, commission: 3.82, orders: 12400 },
  { month: "Feb", revenue: 42.1, commission: 4.21, orders: 13800 },
  { month: "Mar", revenue: 48.7, commission: 4.87, orders: 15200 },
  { month: "Apr", revenue: 52.3, commission: 5.23, orders: 16400 },
  { month: "May", revenue: 55.8, commission: 5.58, orders: 17800 },
  { month: "Jun", revenue: 58.9, commission: 5.89, orders: 19200 },
  { month: "Jul", revenue: 62.4, commission: 6.24, orders: 20800 },
];

export const SERVICE_DEMAND = [
  { name: "Wash & Fold", value: 38, color: "#0d9488" },
  { name: "Wash & Iron", value: 24, color: "#10b981" },
  { name: "Dry Cleaning", value: 16, color: "#8b5cf6" },
  { name: "Premium Care", value: 9, color: "#f59e0b" },
  { name: "Specialty", value: 8, color: "#ec4899" },
  { name: "Bulk", value: 5, color: "#06b6d4" },
];

export const AREA_DEMAND = [
  { area: "Indiranagar", orders: 2840, growth: 14.2 },
  { area: "Koramangala", orders: 3120, growth: 18.6 },
  { area: "HSR Layout", orders: 2180, growth: 22.4 },
  { area: "Whitefield", orders: 1980, growth: 28.1 },
  { area: "Jayanagar", orders: 1640, growth: 8.3 },
  { area: "BTM Layout", orders: 1420, growth: 11.5 },
];

export const WEEKLY_TREND = [
  { day: "Mon", pickups: 142, deliveries: 128 },
  { day: "Tue", pickups: 168, deliveries: 152 },
  { day: "Wed", pickups: 184, deliveries: 176 },
  { day: "Thu", pickups: 198, deliveries: 184 },
  { day: "Fri", pickups: 246, deliveries: 220 },
  { day: "Sat", pickups: 312, deliveries: 286 },
  { day: "Sun", pickups: 268, deliveries: 248 },
];

// ============================================================================
// VENDOR ANALYTICS (for vendor dashboard)
// ============================================================================
export const VENDOR_WEEKLY_REVENUE = [
  { day: "Mon", revenue: 12400, orders: 18 },
  { day: "Tue", revenue: 14200, orders: 22 },
  { day: "Wed", revenue: 16800, orders: 26 },
  { day: "Thu", revenue: 18900, orders: 28 },
  { day: "Fri", revenue: 24600, orders: 34 },
  { day: "Sat", revenue: 31200, orders: 42 },
  { day: "Sun", revenue: 28400, orders: 38 },
];

export const VENDOR_SERVICE_REVENUE = [
  { name: "Wash & Fold", revenue: 84200, color: "#0d9488" },
  { name: "Wash & Iron", revenue: 56800, color: "#10b981" },
  { name: "Dry Cleaning", revenue: 124400, color: "#8b5cf6" },
  { name: "Premium Care", revenue: 64200, color: "#f59e0b" },
  { name: "Steam Ironing", revenue: 38600, color: "#06b6d4" },
];

// ============================================================================
// TIME SLOTS
// ============================================================================
export const PICKUP_SLOTS = [
  { id: "s1", label: "8:00 AM – 10:00 AM", available: true },
  { id: "s2", label: "10:00 AM – 12:00 PM", available: true },
  { id: "s3", label: "12:00 PM – 2:00 PM", available: true },
  { id: "s4", label: "2:00 PM – 4:00 PM", available: false },
  { id: "s5", label: "4:00 PM – 6:00 PM", available: true },
  { id: "s6", label: "6:00 PM – 8:00 PM", available: true },
];

export const DELIVERY_SLOTS = [
  { id: "d1", label: "10:00 AM – 12:00 PM", available: true },
  { id: "d2", label: "12:00 PM – 2:00 PM", available: true },
  { id: "d3", label: "2:00 PM – 4:00 PM", available: true },
  { id: "d4", label: "6:00 PM – 8:00 PM", available: true },
  { id: "d5", label: "8:00 PM – 10:00 PM", available: false },
];

// ============================================================================
// GARMENT INVENTORY (vendor)
// ============================================================================
export const GARMENT_INVENTORY = [
  { id: "g1", type: "Cotton Shirt", brand: "Peter England", qty: 6, color: "White", condition: "Good", notes: "", photos: 2 },
  { id: "g2", type: "Jeans", brand: "Levis", qty: 2, color: "Blue", condition: "Good", notes: "", photos: 1 },
  { id: "g3", type: "T-Shirt", brand: "Nike", qty: 4, color: "Mixed", condition: "Stain on collar", notes: "Pre-treat required", photos: 3 },
  { id: "g4", type: "Bedsheet", brand: "Bombay Dyeing", qty: 1, color: "Cream", condition: "Good", notes: "", photos: 1 },
  { id: "g5", type: "Sherwani", brand: "Manyavar", qty: 1, color: "Maroon", condition: "Premium", notes: "Dry clean only, handle with care", photos: 4 },
  { id: "g6", type: "Saree", brand: "Kanchipuram", qty: 2, color: "Mixed", condition: "Delicate", notes: "Silk — hand wash", photos: 3 },
];
