import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import { authMiddleware } from "./middleware/auth";
import addressesRouter from "./routes/addresses";
import authRouter from "./routes/auth";
import ordersRouter from "./routes/orders";
import vendorsRouter from "./routes/vendors";
import deliveryTasksRouter from "./routes/delivery-tasks";
import deliveryExecutivesRouter from "./routes/delivery-executives";
import notificationsRouter from "./routes/notifications";
import slotsRouter from "./routes/slots";
import walletRouter from "./routes/wallet";
import reviewsRouter from "./routes/reviews";
import servicesRouter from "./routes/services";
import couponsRouter from "./routes/coupons";
import adminRouter from "./routes/admin";
import vendorAnalyticsRouter from "./routes/vendor-analytics";
import subscriptionsRouter from "./routes/subscriptions";
import vendorStaffRouter from "./routes/vendor-staff";
import garmentsRouter from "./routes/garments";
import walletMethodsRouter from "./routes/wallet-methods";
import couponValidateRouter from "./routes/coupon-validate";
import supportTicketsRouter from "./routes/support-tickets";
import adminCampaignsRouter from "./routes/admin-campaigns";
import adminFeaturesRouter from "./routes/admin-features";
import adminAuditLogsRouter from "./routes/admin-audit-logs";
import adminIntegrationsRouter from "./routes/admin-integrations";
import adminReportsRouter from "./routes/admin-reports";
import adminUsersRouter from "./routes/admin-users";
import adminConfigRouter from "./routes/admin-config";
import adminRbacRouter from "./routes/admin-rbac";
import adminCommissionRouter from "./routes/admin-commission";
import orderStagesRouter from "./routes/order-stages";
import chatRouter from "./routes/chat";
import favoritesRouter from "./routes/favorites";
import geocodeRouter from "./routes/geocode";
import routingRouter from "./routes/routing";
import deliveryLocationRouter from "./routes/delivery-location";
import vendorOnboardingRouter from "./routes/vendor-onboarding";
import paymentsRouter from "./routes/payments";

const app = express();

app.use(cors({ origin: true, credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use(authMiddleware);

// API Routes
app.get("/api", (_req, res) => res.json({ message: "Laundry Home API" }));
app.use("/api/auth", authRouter);
app.use("/api/orders", ordersRouter);
app.use("/api/vendors", vendorsRouter);
app.use("/api/addresses", addressesRouter);
app.use("/api/delivery-tasks", deliveryTasksRouter);
app.use("/api/delivery-executives", deliveryExecutivesRouter);
app.use("/api/notifications", notificationsRouter);
app.use("/api/slots", slotsRouter);
app.use("/api/wallet", walletRouter);
app.use("/api/reviews", reviewsRouter);
app.use("/api/services", servicesRouter);
app.use("/api/coupons", couponsRouter);
app.use("/api/admin", adminRouter);
app.use("/api/vendor/analytics", vendorAnalyticsRouter);
app.use("/api/subscriptions", subscriptionsRouter);
app.use("/api/vendor/staff", vendorStaffRouter);
app.use("/api/garments", garmentsRouter);
app.use("/api/wallet/methods", walletMethodsRouter);
app.use("/api/coupons/validate", couponValidateRouter);
app.use("/api/support/tickets", supportTicketsRouter);
app.use("/api/admin/campaigns", adminCampaignsRouter);
app.use("/api/admin/features", adminFeaturesRouter);
app.use("/api/admin/audit-logs", adminAuditLogsRouter);
app.use("/api/admin/integrations", adminIntegrationsRouter);
app.use("/api/admin/reports", adminReportsRouter);
app.use("/api/admin/users", adminUsersRouter);
app.use("/api/admin/config", adminConfigRouter);
app.use("/api/admin/rbac", adminRbacRouter);
app.use("/api/admin/commission", adminCommissionRouter);
app.use("/api/order-stages", orderStagesRouter);
app.use("/api/chat", chatRouter);
app.use("/api/favorites", favoritesRouter);
app.use("/api/geocode", geocodeRouter);
app.use("/api/routing", routingRouter);
app.use("/api/delivery/location", deliveryLocationRouter);
app.use("/api/vendor/onboarding", vendorOnboardingRouter);
app.use("/api/payments", paymentsRouter);

export default app;
